export const countryList = [
  { name: 'Afghanistan', isoCode: 'AF', phonePrefix: '+93' },
  { name: 'Albania', isoCode: 'AL', phonePrefix: '+355' },
  { name: 'Algeria', isoCode: 'DZ', phonePrefix: '+213' },
  { name: 'Andorra', isoCode: 'AD', phonePrefix: '+376' },
  { name: 'Angola', isoCode: 'AO', phonePrefix: '+244' },
  { name: 'Anguilla', isoCode: 'AI', phonePrefix: '+1-264' },
  { name: 'Antigua & Barbuda', isoCode: 'AG', phonePrefix: '+1-268' },
  { name: 'Argentina', isoCode: 'AR', phonePrefix: '+54' },
  { name: 'Armenia', isoCode: 'AM', phonePrefix: '+374' },
  { name: 'Aruba', isoCode: 'AW', phonePrefix: '+297' },
  { name: 'Australia', isoCode: 'AU', phonePrefix: '+61' },
  { name: 'Austria', isoCode: 'AT', phonePrefix: '+43' },
  { name: 'Azerbaijan', isoCode: 'AZ', phonePrefix: '+994' },
  { name: 'Bahamas', isoCode: 'BS', phonePrefix: '+1-242' },
  { name: 'Bahrain', isoCode: 'BH', phonePrefix: '+973' },
  { name: 'Bangladesh', isoCode: 'BD', phonePrefix: '+880' },
  { name: 'Barbados', isoCode: 'BB', phonePrefix: '+1-246' },
  { name: 'Belarus', isoCode: 'BY', phonePrefix: '+375' },
  { name: 'Belgium', isoCode: 'BE', phonePrefix: '+32' },
  { name: 'Belize', isoCode: 'BZ', phonePrefix: '+501' },
  { name: 'Benin', isoCode: 'BJ', phonePrefix: '+229' },
  { name: 'Bermuda', isoCode: 'BM', phonePrefix: '+1-441' },
  { name: 'Bhutan', isoCode: 'BT', phonePrefix: '+975' },
  { name: 'Bolivia', isoCode: 'BO', phonePrefix: '+591' },
  { name: 'Bosnia & Herzegovina', isoCode: 'BA', phonePrefix: '+387' },
  { name: 'Botswana', isoCode: 'BW', phonePrefix: '+267' },
  { name: 'Brazil', isoCode: 'BR', phonePrefix: '+55' },
  { name: 'British Virgin Islands', isoCode: 'VG', phonePrefix: '+1-284' },
  { name: 'Brunei', isoCode: 'BN', phonePrefix: '+673' },
  { name: 'Bulgaria', isoCode: 'BG', phonePrefix: '+359' },
  { name: 'Burkina Faso', isoCode: 'BF', phonePrefix: '+226' },
  { name: 'Burundi', isoCode: 'BI', phonePrefix: '+257' },
  { name: 'Cambodia', isoCode: 'KH', phonePrefix: '+855' },
  { name: 'Cameroon', isoCode: 'CM', phonePrefix: '+237' },
  { name: 'Canada', isoCode: 'CA', phonePrefix: '+1' },
  { name: 'Cape Verde', isoCode: 'CV', phonePrefix: '+238' },
  { name: 'Cayman Islands', isoCode: 'KY', phonePrefix: '+1-345' },
  { name: 'Central African Republic', isoCode: 'CF', phonePrefix: '+236' },
  { name: 'Chad', isoCode: 'TD', phonePrefix: '+235' },
  { name: 'Chile', isoCode: 'CL', phonePrefix: '+56' },
  { name: 'China', isoCode: 'CN', phonePrefix: '+86' },
  { name: 'Colombia', isoCode: 'CO', phonePrefix: '+57' },
  { name: 'Comoros', isoCode: 'KM', phonePrefix: '+269' },
  { name: 'Congo', isoCode: 'CG', phonePrefix: '+242' },
  { name: 'Cook Islands', isoCode: 'CK', phonePrefix: '+682' },
  { name: 'Costa Rica', isoCode: 'CR', phonePrefix: '+506' },
  { name: 'Cote D Ivoire', isoCode: 'CI', phonePrefix: '+225' },
  { name: 'Croatia', isoCode: 'HR', phonePrefix: '+385' },
  { name: 'Cuba', isoCode: 'CU', phonePrefix: '+53' },
  { name: 'Curacao', isoCode: 'CW', phonePrefix: '+599' },
  { name: 'Cyprus', isoCode: 'CY', phonePrefix: '+357' },
  { name: 'Czech Republic', isoCode: 'CZ', phonePrefix: '+420' },
  { name: 'Democratic Republic of Congo', isoCode: 'CD', phonePrefix: '+243' },
  { name: 'Denmark', isoCode: 'DK', phonePrefix: '+45' },
  { name: 'Djibouti', isoCode: 'DJ', phonePrefix: '+253' },
  { name: 'Dominica', isoCode: 'DM', phonePrefix: '+1-767' },
  {
    name: 'Dominican Republic',
    isoCode: 'DO',
    phonePrefix: '+1-809, +1-829, +1-849',
  },
  { name: 'Ecuador', isoCode: 'EC', phonePrefix: '+593' },
  { name: 'Egypt', isoCode: 'EG', phonePrefix: '+20' },
  { name: 'El Salvador', isoCode: 'SV', phonePrefix: '+503' },
  { name: 'Equatorial Guinea', isoCode: 'GQ', phonePrefix: '+240' },
  { name: 'Eritrea', isoCode: 'ER', phonePrefix: '+291' },
  { name: 'Estonia', isoCode: 'EE', phonePrefix: '+372' },
  { name: 'Eswatini', isoCode: 'SZ', phonePrefix: '+268' },
  { name: 'Ethiopia', isoCode: 'ET', phonePrefix: '+251' },
  { name: 'Falkland Islands', isoCode: 'FK', phonePrefix: '+500' },
  { name: 'Faroe Islands', isoCode: 'FO', phonePrefix: '+298' },
  { name: 'Fiji', isoCode: 'FJ', phonePrefix: '+679' },
  { name: 'Finland', isoCode: 'FI', phonePrefix: '+358' },
  { name: 'France', isoCode: 'FR', phonePrefix: '+33' },
  { name: 'French Guiana', isoCode: 'GF', phonePrefix: '+594' },
  { name: 'French Polynesia', isoCode: 'PF', phonePrefix: '+689' },
  { name: 'Gabon', isoCode: 'GA', phonePrefix: '+241' },
  { name: 'Gambia', isoCode: 'GM', phonePrefix: '+220' },
  { name: 'Georgia', isoCode: 'GE', phonePrefix: '+995' },
  { name: 'Germany', isoCode: 'DE', phonePrefix: '+49' },
  { name: 'Ghana', isoCode: 'GH', phonePrefix: '+233' },
  { name: 'Gibraltar', isoCode: 'GI', phonePrefix: '+350' },
  { name: 'Greece', isoCode: 'GR', phonePrefix: '+30' },
  { name: 'Greenland', isoCode: 'GL', phonePrefix: '+299' },
  { name: 'Grenada', isoCode: 'GD', phonePrefix: '+1-473' },
  { name: 'Guadeloupe', isoCode: 'GP', phonePrefix: '+590' },
  { name: 'Guam', isoCode: 'GU', phonePrefix: '+1-671' },
  { name: 'Guatemala', isoCode: 'GT', phonePrefix: '+502' },
  { name: 'Guernsey', isoCode: 'GG', phonePrefix: '+44-1481' },
  { name: 'Guinea', isoCode: 'GN', phonePrefix: '+224' },
  { name: 'Guinea Bissau', isoCode: 'GW', phonePrefix: '+245' },
  { name: 'Guyana', isoCode: 'GY', phonePrefix: '+592' },
  { name: 'Haiti', isoCode: 'HT', phonePrefix: '+509' },
  { name: 'Honduras', isoCode: 'HN', phonePrefix: '+504' },
  { name: 'Hong Kong', isoCode: 'HK', phonePrefix: '+852' },
  { name: 'Hungary', isoCode: 'HU', phonePrefix: '+36' },
  { name: 'Iceland', isoCode: 'IS', phonePrefix: '+354' },
  { name: 'India', isoCode: 'IN', phonePrefix: '+91' },
  { name: 'Indonesia', isoCode: 'ID', phonePrefix: '+62' },
  { name: 'Iran', isoCode: 'IR', phonePrefix: '+98' },
  { name: 'Iraq', isoCode: 'IQ', phonePrefix: '+964' },
  { name: 'Ireland', isoCode: 'IE', phonePrefix: '+353' },
  { name: 'Isle of Man', isoCode: 'IM', phonePrefix: '+44-1624' },
  { name: 'Israel', isoCode: 'IL', phonePrefix: '+972' },
  { name: 'Italy', isoCode: 'IT', phonePrefix: '+39' },
  { name: 'Jamaica', isoCode: 'JM', phonePrefix: '+1-876' },
  { name: 'Japan', isoCode: 'JP', phonePrefix: '+81' },
  { name: 'Jersey', isoCode: 'JE', phonePrefix: '+44-1534' },
  { name: 'Jordan', isoCode: 'JO', phonePrefix: '+962' },
  { name: 'Kazakhstan', isoCode: 'KZ', phonePrefix: '+7' },
  { name: 'Kenya', isoCode: 'KE', phonePrefix: '+254' },
  { name: 'Kiribati', isoCode: 'KI', phonePrefix: '+686' },
  { name: 'Kosovo', isoCode: 'XK', phonePrefix: '+383' },
  { name: 'Kuwait', isoCode: 'KW', phonePrefix: '+965' },
  { name: 'Kyrgyz Republic', isoCode: 'KG', phonePrefix: '+996' },
  { name: 'Laos', isoCode: 'LA', phonePrefix: '+856' },
  { name: 'Latvia', isoCode: 'LV', phonePrefix: '+371' },
  { name: 'Lebanon', isoCode: 'LB', phonePrefix: '+961' },
  { name: 'Lesotho', isoCode: 'LS', phonePrefix: '+266' },
  { name: 'Liberia', isoCode: 'LR', phonePrefix: '+231' },
  { name: 'Libya', isoCode: 'LY', phonePrefix: '+218' },
  { name: 'Liechtenstein', isoCode: 'LI', phonePrefix: '+423' },
  { name: 'Lithuania', isoCode: 'LT', phonePrefix: '+370' },
  { name: 'Luxembourg', isoCode: 'LU', phonePrefix: '+352' },
  { name: 'Macau', isoCode: 'MO', phonePrefix: '+853' },
  { name: 'Madagascar', isoCode: 'MG', phonePrefix: '+261' },
  { name: 'Malawi', isoCode: 'MW', phonePrefix: '+265' },
  { name: 'Malaysia', isoCode: 'MY', phonePrefix: '+60' },
  { name: 'Maldives', isoCode: 'MV', phonePrefix: '+960' },
  { name: 'Mali', isoCode: 'ML', phonePrefix: '+223' },
  { name: 'Malta', isoCode: 'MT', phonePrefix: '+356' },
  { name: 'Marshall Islands', isoCode: 'MH', phonePrefix: '+692' },
  { name: 'Martinique', isoCode: 'MQ', phonePrefix: '+596' },
  { name: 'Mauritania', isoCode: 'MR', phonePrefix: '+222' },
  { name: 'Mauritius', isoCode: 'MU', phonePrefix: '+230' },
  { name: 'Mexico', isoCode: 'MX', phonePrefix: '+52' },
  { name: 'Micronesia', isoCode: 'FM', phonePrefix: '+691' },
  { name: 'Moldova', isoCode: 'MD', phonePrefix: '+373' },
  { name: 'Monaco', isoCode: 'MC', phonePrefix: '+377' },
  { name: 'Mongolia', isoCode: 'MN', phonePrefix: '+976' },
  { name: 'Montenegro', isoCode: 'ME', phonePrefix: '+382' },
  { name: 'Montserrat', isoCode: 'MS', phonePrefix: '+1-664' },
  { name: 'Morocco', isoCode: 'MA', phonePrefix: '+212' },
  { name: 'Mozambique', isoCode: 'MZ', phonePrefix: '+258' },
  { name: 'Myanmar', isoCode: 'MM', phonePrefix: '+95' },
  { name: 'Namibia', isoCode: 'NA', phonePrefix: '+264' },
  { name: 'Nauru', isoCode: 'NR', phonePrefix: '+674' },
  { name: 'Nepal', isoCode: 'NP', phonePrefix: '+977' },
  { name: 'Netherlands', isoCode: 'NL', phonePrefix: '+31' },
  { name: 'Netherlands Antilles', isoCode: 'AN', phonePrefix: '+599' },
  { name: 'New Caledonia', isoCode: 'NC', phonePrefix: '+687' },
  { name: 'New Zealand', isoCode: 'NZ', phonePrefix: '+64' },
  { name: 'Nicaragua', isoCode: 'NI', phonePrefix: '+505' },
  { name: 'Niger', isoCode: 'NE', phonePrefix: '+227' },
  { name: 'Nigeria', isoCode: 'NG', phonePrefix: '+234' },
  { name: 'North Korea', isoCode: 'KP', phonePrefix: '+850' },
  { name: 'North Macedonia', isoCode: 'MK', phonePrefix: '+389' },
  { name: 'Norway', isoCode: 'NO', phonePrefix: '+47' },
  { name: 'Oman', isoCode: 'OM', phonePrefix: '+968' },
  { name: 'Pakistan', isoCode: 'PK', phonePrefix: '+92' },
  { name: 'Palau', isoCode: 'PW', phonePrefix: '+680' },
  { name: 'Palestine', isoCode: 'PS', phonePrefix: '+970' },
  { name: 'Panama', isoCode: 'PA', phonePrefix: '+507' },
  { name: 'Papua New Guinea', isoCode: 'PG', phonePrefix: '+675' },
  { name: 'Paraguay', isoCode: 'PY', phonePrefix: '+595' },
  { name: 'Peru', isoCode: 'PE', phonePrefix: '+51' },
  { name: 'Philippines', isoCode: 'PH', phonePrefix: '+63' },
  { name: 'Poland', isoCode: 'PL', phonePrefix: '+48' },
  { name: 'Portugal', isoCode: 'PT', phonePrefix: '+351' },
  { name: 'Puerto Rico', isoCode: 'PR', phonePrefix: '+1-787, +1-939' },
  { name: 'Qatar', isoCode: 'QA', phonePrefix: '+974' },
  { name: 'Reunion', isoCode: 'RE', phonePrefix: '+262' },
  { name: 'Romania', isoCode: 'RO', phonePrefix: '+40' },
  { name: 'Russia', isoCode: 'RU', phonePrefix: '+7' },
  { name: 'Rwanda', isoCode: 'RW', phonePrefix: '+250' },
  { name: 'Saint Barthelemy', isoCode: 'BL', phonePrefix: '+590' },
  { name: 'Saint Helena', isoCode: 'SH', phonePrefix: '+290' },
  { name: 'Saint Kitts & Nevis', isoCode: 'KN', phonePrefix: '+1-869' },
  { name: 'Saint Lucia', isoCode: 'LC', phonePrefix: '+1-758' },
  { name: 'Saint Martin', isoCode: 'MF', phonePrefix: '+590' },
  { name: 'Saint Pierre & Miquelon', isoCode: 'PM', phonePrefix: '+508' },
  {
    name: 'Saint Vincent & the Grenadines',
    isoCode: 'VC',
    phonePrefix: '+1-784',
  },
  { name: 'Samoa', isoCode: 'WS', phonePrefix: '+685' },
  { name: 'San Marino', isoCode: 'SM', phonePrefix: '+378' },
  { name: 'Sao Tome & Principe', isoCode: 'ST', phonePrefix: '+239' },
  { name: 'Saudi Arabia', isoCode: 'SA', phonePrefix: '+966' },
  { name: 'Senegal', isoCode: 'SN', phonePrefix: '+221' },
  { name: 'Serbia', isoCode: 'RS', phonePrefix: '+381' },
  { name: 'Seychelles', isoCode: 'SC', phonePrefix: '+248' },
  { name: 'Sierra Leone', isoCode: 'SL', phonePrefix: '+232' },
  { name: 'Singapore', isoCode: 'SG', phonePrefix: '+65' },
  { name: 'Sint Maarten', isoCode: 'SX', phonePrefix: '+1-721' },
  { name: 'Slovakia', isoCode: 'SK', phonePrefix: '+421' },
  { name: 'Slovenia', isoCode: 'SI', phonePrefix: '+386' },
  { name: 'Solomon Islands', isoCode: 'SB', phonePrefix: '+677' },
  { name: 'Somalia', isoCode: 'SO', phonePrefix: '+252' },
  { name: 'South Africa', isoCode: 'ZA', phonePrefix: '+27' },
  { name: 'South Korea', isoCode: 'KR', phonePrefix: '+82' },
  { name: 'South Sudan', isoCode: 'SS', phonePrefix: '+211' },
  { name: 'Spain', isoCode: 'ES', phonePrefix: '+34' },
  { name: 'Sri Lanka', isoCode: 'LK', phonePrefix: '+94' },
  { name: 'Sudan', isoCode: 'SD', phonePrefix: '+249' },
  { name: 'Suriname', isoCode: 'SR', phonePrefix: '+597' },
  { name: 'Sweden', isoCode: 'SE', phonePrefix: '+46' },
  { name: 'Switzerland', isoCode: 'CH', phonePrefix: '+41' },
  { name: 'Syria', isoCode: 'SY', phonePrefix: '+963' },
  { name: 'Taiwan', isoCode: 'TW', phonePrefix: '+886' },
  { name: 'Tajikistan', isoCode: 'TJ', phonePrefix: '+992' },
  { name: 'Tanzania', isoCode: 'TZ', phonePrefix: '+255' },
  { name: 'Thailand', isoCode: 'TH', phonePrefix: '+66' },
  { name: "Timor L'Este", isoCode: 'TL', phonePrefix: '+670' },
  { name: 'Togo', isoCode: 'TG', phonePrefix: '+228' },
  { name: 'Tonga', isoCode: 'TO', phonePrefix: '+676' },
  { name: 'Trinidad & Tobago', isoCode: 'TT', phonePrefix: '+1-868' },
  { name: 'Tunisia', isoCode: 'TN', phonePrefix: '+216' },
  { name: 'Turkey', isoCode: 'TR', phonePrefix: '+90' },
  { name: 'Turkmenistan', isoCode: 'TM', phonePrefix: '+993' },
  { name: 'Turks & Caicos', isoCode: 'TC', phonePrefix: '+1-649' },
  { name: 'Tuvalu', isoCode: 'TV', phonePrefix: '+688' },
  { name: 'Uganda', isoCode: 'UG', phonePrefix: '+256' },
  { name: 'Ukraine', isoCode: 'UA', phonePrefix: '+380' },
  { name: 'United Arab Emirates', isoCode: 'AE', phonePrefix: '+971' },
  { name: 'United Kingdom', isoCode: 'GB', phonePrefix: '+44' },
  { name: 'United States', isoCode: 'US', phonePrefix: '+1' },
  { name: 'Uruguay', isoCode: 'UY', phonePrefix: '+598' },
  { name: 'Uzbekistan', isoCode: 'UZ', phonePrefix: '+998' },
  { name: 'Vanuatu', isoCode: 'VU', phonePrefix: '+678' },
  { name: 'Vatican City', isoCode: 'VA', phonePrefix: '+379' },
  { name: 'Venezuela', isoCode: 'VE', phonePrefix: '+58' },
  { name: 'Vietnam', isoCode: 'VN', phonePrefix: '+84' },
  { name: 'Virgin Islands (US)', isoCode: 'VI', phonePrefix: '+1-340' },
  { name: 'Wallis & Futuna', isoCode: 'WF', phonePrefix: '+681' },
  { name: 'Yemen', isoCode: 'YE', phonePrefix: '+967' },
  { name: 'Zambia', isoCode: 'ZM', phonePrefix: '+260' },
  { name: 'Zimbabwe', isoCode: 'ZW', phonePrefix: '+263' },
];
