import { NotificationDTO } from '../shared/models/notification.mode';

// hard coded data for testing.
export const notificationDemoData: NotificationDTO[] = [
  {
    _id: '1234',
    recipients: ['nltdev'],
    message: 'Test demo notification.',
    dateSent: 1695207686323,
    seenBy: [],
    createdBy: '',
    schoolId: '',
  },
  {
    _id: '1234',
    recipients: ['nltdev'],
    message: 'System restart sceduled in 15 mins.',
    dateSent: 1709076379001,
    seenBy: [],
    createdBy: '',
    schoolId: '',
  },
  {
    _id: '1234',
    recipients: ['nltdev'],
    message: 'Send me your location',
    dateSent: 1684070487967,
    seenBy: ['nltdev'],
    createdBy: '',
    schoolId: '',
  },
  {
    _id: '1234',
    recipients: ['nltdev', 'Barry Smith', 'Alice Smith'],
    message:
      'This is a test notification of a great length so I can test to see how the notification window handles x-overflow. I hope it goes well. Fingers crossed. This should be long enough now. I should really use Lorem Ispum for this, it would be much quicker than typing something out.',
    dateSent: 1674912788222,
    seenBy: ['nltdev', 'Barry Smith'],
    createdBy: '',
    schoolId: '',
  },
  {
    _id: '1234',
    recipients: ['Emma Thompson'],
    message: 'Test Notificaiton 2',
    dateSent: 1712065097450,
    seenBy: ['nltdev'],
    createdBy: '',
    schoolId: '',
  },
  {
    _id: '1234',
    recipients: ['Alice Smith', 'nltdev'],
    message: 'System error',
    dateSent: 1667089699953,
    seenBy: ['nltdev'],
    createdBy: '',
    schoolId: '',
  },
  {
    _id: '1234',
    recipients: ['David Brown', 'nltdev'],
    message:
      'Reminder: Team lunch at 12:00 PM today. Make sure you do not miss it. There will be a presentation on testing how to display long text like this in a message preview.',
    dateSent: 1692671636333,
    seenBy: ['nltdev'],
    createdBy: '',
    schoolId: '',
  },
  {
    _id: '1234',
    recipients: ['Jennifer Wilson', 'nltdev'],
    message: 'Congratulations on your promotion!',
    dateSent: 1654374069066,
    seenBy: ['nltdev'],
    createdBy: '',
    schoolId: '',
  },
  {
    _id: '1234',
    recipients: ['nltdev'],
    message: 'Notification Test 4',
    dateSent: 1691813244779,
    seenBy: ['nltdev'],
    createdBy: '',
    schoolId: '',
  },
  {
    _id: '1234',
    recipients: ['nltdev'],
    message: 'I am running out of things to write in these demo notifications.',
    dateSent: 1654705574210,
    seenBy: ['nltdev'],
    createdBy: '',
    schoolId: '',
  },
  {
    _id: '1234',
    recipients: ['nltdev'],
    message: 'Another Test',
    dateSent: 1717409572607,
    seenBy: ['nltdev'],
    createdBy: '',
    schoolId: '',
  },
  {
    _id: '1234',
    recipients: ['nltdev'],
    message: 'Another Test1',
    dateSent: 1717394400000,
    seenBy: ['nltdev'],
    createdBy: '',
    schoolId: '',
  },
  {
    _id: '1234',
    recipients: ['nltdev'],
    message: 'Another Test2',
    dateSent: 1717221600000,
    seenBy: ['nltdev'],
    createdBy: '',
    schoolId: '',
  },
  {
    _id: '1234',
    recipients: ['nltdev'],
    message: 'Another Test3',
    dateSent: 1716184800000,
    seenBy: ['nltdev'],
    createdBy: '',
    schoolId: '',
  },
  {
    _id: '1234',
    recipients: ['nltdev'],
    message: 'Another Test4',
    dateSent: 1710918000000,
    seenBy: ['nltdev'],
    createdBy: '',
    schoolId: '',
  },
  {
    _id: '1234',
    recipients: ['nltdev'],
    message: 'Another Test5',
    dateSent: 1679295600000,
    seenBy: ['nltdev'],
    createdBy: '',
    schoolId: '',
  },
];
